interval: 2s

wans:
  # ---------------------------------
  # WAN 1: ACT
  # ---------------------------------
  - name: ACT
    interface: eth0
    targets:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
    tcp_targets:
      - "1.1.1.1:443"
      - "8.8.8.8:443"
      - "9.9.9.9:443"
    on_down: []
    on_up: []
    threshold:
      latency: 250
      latency_samples: 40
      loss: 5
      loss_samples: 40
      jitter: 50
      jitter_samples: 40

  # ---------------------------------
  # WAN 2: Hathway
  # ---------------------------------
  - name: Hathway
    interface: eth2
    targets:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
    tcp_targets:
      - "1.1.1.1:443"
      - "8.8.8.8:443"
      - "9.9.9.9:443"
    on_down: []
    on_up: []
    threshold:
      latency: 250
      latency_samples: 40
      loss: 5
      loss_samples: 40
      jitter: 50
      jitter_samples: 40

  # ---------------------------------
  # WAN 3: Airtel
  # ---------------------------------
  - name: Airtel
    interface: eth3
    targets:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
    tcp_targets:
      - "1.1.1.1:443"
      - "8.8.8.8:443"
      - "9.9.9.9:443"
    on_down: []
    on_up: []
    threshold:
      latency: 250
      latency_samples: 40
      loss: 5
      loss_samples: 40
      jitter: 50
      jitter_samples: 40
